### ISSUE TITLE
v1.2.1 Zippering when applying aftertouch to VCFs / aftertouch response should be smoothed

### ISSUE THREAD

**Issue by schillp5** [ffont/official-ddrm-issue-tracker#10]
Audible zippering when filter cutoff aftertouch mod is set to max.

Most synths use running averages, and hysteresis to smooth pressure response in firmware.  From Geert Bevin: 
"most synths do not react immediately to MIDI changes, otherwise it sounds bad. internally you usually have a high resolution variable that you slew towards the value that was sent, so even if the resolution of the MIDI stream is 7 bit, internally the resolution is much higher and it sounds super smooth. That's probably what they (DD programmer) need to do"

**Comment by ffont** [comment]
This seems related to https://github.com/ffont/ddrm-issues/issues/5, it's probably the same problem.

**Comment by ffont** [comment]
I see now that this issue (which I also experienced) is not really related to #5. The fix here would probably be to smooth the stream of pressure messages that arrive to the DD as @schillp5 describes in his message.

**Comment by schillp5** [comment]
Here is an audio demo of the zippering. It literally sounds like a zipper!
https://soundcloud.com/paul-schilling/dd-at-zippering/s-eDPhQ

**Comment by ffont** [comment]
Thanks for the sound example @schillp5. Maybe we could ping DD team now pointing to this issue list. I know they are aware of its existence but I don't think they actively check it. They reported being  working (at least) on fixing issues #2 and #5, but I don't know about the others. Hmm if the software was open sourced we could fix it ourselves :)

**Comment by MrPandoman** [comment]
It seems like the zippering noise does not even affect sound, leading me to speculate that it could be electrical interference (crosstalk) from MIDI data transmission in the sound card, outboard mixer, or cables. I've never heard this in my unit. Most of the zippering noise I hear is related to low resolution (steps) on the sliders, especially filters.

**Comment by schillp5** [comment]
...or could it electrical interference inside the DD? Since the MIDI input is so close to the audio output, and aftertouch is the only MIDI signal of which there is a massive amount? 

I'm almost positive I can reproduce this with my MIDI controller plugged directly in to the MIDI DIN port of the DD, rather than going through an audio interface with MIDI.

The easiest way to reproduce this is to play extremely high notes, where the zippering noise-to-note ratio is much higher

**Comment by ffont** [comment]
@schillp5 this problem was also observed in firmware versions other than 1.2.1 right? I'd remove 1.2.1 from the title and add it to the issue description. I think it might be  better to do this for all the issues which happen across versions.
