### ISSUE TITLE
Jitter in Filter sliders

### ISSUE THREAD

**Issue by ffont** [ffont/official-ddrm-issue-tracker#5]
Filter sliders present have some Jitter which results in sometimes audible effects. There has been a long discussion about that in the FB group: https://www.facebook.com/groups/deckardsdream/search/?query=jitter. Some users reported this only happens in the mid range of the sliders.

Apparently it still needs a fix from the designers of DD.

(more work should be done here to better explain the issue and probably put examples and steps to reproduce to help the DD team fix it)

**Comment by schillp5** [comment]
This is a serious, clearly audible issue, and can be so easily fixed using simple hysteresis and running-averages techniques in the firmware code.

**Comment by ffont** [comment]
> This is a serious, clearly audible issue, and can be so easily fixed using simple hysteresis and running-averages techniques in the firmware code.

I think DD is already taking doing some hysteresis, but Roman/Bob should check on that to get a  definitive fix for the problem.

**Comment by ffont** [comment]
I got confirmation from Black Corporation that they're working on a fix for that issue. This will also fix #2 and probably #10.

**Comment by schillp5** [comment]
In the upcoming version (1.2.4), the filter jitter has been minimized by introducing hysteresis/lag to the slider reading. The jitter is now confined to jumps of 1, occurs less frequently and in a more limited slider range.

**Comment by ffont** [comment]
This problem is still happening in FW 1.2.5 (see related issue #2 and the output of the MIDI monitor I made: https://github.com/ffont/official-ddrm-issue-tracker/issues/2#issuecomment-398824562). Might not be super audible but it is there.

**Comment by ffont** [comment]
Closing as this has been fixed in later firmware versions.
